#pragma once

enum ItemToolTier : char
{
	TOOL_TIER_WOOD,
	TOOL_TIER_STONE,
	TOOL_TIER_IRON,
	TOOL_TIER_DIAMOND,
	TOOL_TIER_GOLD,
	TOOL_TIER_NONE = 127,
};

enum ItemToolType : char
{
	TOOL_TYPE_SHOVEL,
	TOOL_TYPE_PICKAXE,
	TOOL_TYPE_AXE,
	TOOL_TYPE_SWORD,
	TOOL_TYPE_HOE,
	TOOL_TYPE_FLINT_AND_STEEL,
	TOOL_TYPE_ARMOR_HEAD,
	TOOL_TYPE_ARMOR_CHEST,
	TOOL_TYPE_ARMOR_LEGS,
	TOOL_TYPE_ARMOR_FEET,
	TOOL_TYPE_NONE = 127,
};